pub const TACTICAL_LABELS: [&str; 28] = [
    "NOMINAL_IDLE", "SYSTEM_HEARTBEAT", "KERNEL_SIGNAL", "APP_LIFECYCLE",
    "NETWORK_NEGOTIATION", "MEMORY_ALLOCATION", "THERMAL_THROTTLE_RISK", "IO_CONGESTION",
    "PROCESS_ESCALATION", "SECURITY_AUDIT_LOG", "DATABASE_SYNC", "UID_VALIDATION",
    "INTERRUPT_VECTOR", "DRIVER_HANDSHAKE", "POWER_STATE_SHIFT", "CACHE_INVALIDATION",
    "DAEMON_RESPAWN", "BUFFER_OVERFLOW_GUARD", "LOGCAT_OVERFLOW", "API_TIMEOUT",
    "CONTAINER_ISOLATION", "HARDWARE_EXCEPTION", "CRYPTOGRAPHIC_LOCK", "SIGNAL_FRAGMENTATION",
    "ZOMBIE_PROCESS_CLEANUP", "STABILITY_DRIFT", "UNKNOWN_ANOMALY", "NEXUS_SYNC_FAILURE"
];
